services:
  nextjs:
    build:
      dockerfile: nextjs/Dockerfile.prod
    container_name: nextjs
    extra_hosts:
      # コンテナ内部のdnsではAPI routesでバックエンド側のドメインを名前解決できないため
      # 本当はホスト側のlocalhostに接続したいが、localhostの挙動が特殊なためルーターを経由して外からのアクセスと同等にしている
      - 'sms.cypas.sec:${HOST_IP}'
      - 'cms.cypas.sec:${HOST_IP}'
    ports:
      - 8000:8000
    depends_on:
      - mysql

    restart: on-failure
  mysql:
    build:
      context: ./mysql
      dockerfile: Dockerfile.prod
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      TZ: 'Asia/Tokyo'
    volumes:
      - mysql-db-store:/var/lib/mysql

volumes:
  mysql-db-store:
